import { PERMISSIONS } from "./permissions";
import { ROLES } from "./roles";

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD.READ,

    PERMISSIONS.USERS.READ,
    PERMISSIONS.USERS.CREATE,
    PERMISSIONS.USERS.UPDATE,
    PERMISSIONS.USERS.DELETE,

    PERMISSIONS.WORK_ITEMS.READ,
    PERMISSIONS.WORK_ITEMS.CREATE,
    PERMISSIONS.WORK_ITEMS.UPDATE,
    PERMISSIONS.WORK_ITEMS.DELETE,

    PERMISSIONS.PROFILE.READ,
    PERMISSIONS.PROFILE.UPDATE,

    PERMISSIONS.SETTINGS.READ,
    PERMISSIONS.SETTINGS.UPDATE,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD.READ,

    PERMISSIONS.USERS.READ,
    PERMISSIONS.USERS.UPDATE,

    PERMISSIONS.WORK_ITEMS.READ,
    PERMISSIONS.WORK_ITEMS.CREATE,
    PERMISSIONS.WORK_ITEMS.UPDATE,

    PERMISSIONS.PROFILE.READ,
    PERMISSIONS.PROFILE.UPDATE,
  ],

  [ROLES.CONTRIBUTOR]: [
    PERMISSIONS.DASHBOARD.READ,

    PERMISSIONS.WORK_ITEMS.READ,
    PERMISSIONS.WORK_ITEMS.UPDATE,

    PERMISSIONS.PROFILE.READ,
    PERMISSIONS.PROFILE.UPDATE,
  ],
} as const;