import { PERMISSIONS, type Permission } from "./permissions";
import { ROLES, type Role } from "./roles";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.ADMIN]: [
    PERMISSIONS.DASHBOARD.READ,

    PERMISSIONS.USERS.READ,
    PERMISSIONS.USERS.CREATE,
    PERMISSIONS.USERS.UPDATE,
    PERMISSIONS.USERS.DELETE,

    PERMISSIONS.WORK_ITEMS.READ,
    PERMISSIONS.WORK_ITEMS.CREATE,
    PERMISSIONS.WORK_ITEMS.UPDATE,
    PERMISSIONS.WORK_ITEMS.DELETE,

    PERMISSIONS.PROFILE.READ,
    PERMISSIONS.PROFILE.UPDATE,

    PERMISSIONS.SETTINGS.READ,
    PERMISSIONS.SETTINGS.UPDATE,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD.READ,

    PERMISSIONS.USERS.READ,
    PERMISSIONS.USERS.UPDATE,

    PERMISSIONS.WORK_ITEMS.READ,
    PERMISSIONS.WORK_ITEMS.CREATE,
    PERMISSIONS.WORK_ITEMS.UPDATE,

    PERMISSIONS.PROFILE.READ,
    PERMISSIONS.PROFILE.UPDATE,

     // Settings
    PERMISSIONS.SETTINGS.READ,
    PERMISSIONS.SETTINGS.UPDATE,
  ],

  [ROLES.CONTRIBUTOR]: [
    PERMISSIONS.DASHBOARD.READ,

    PERMISSIONS.WORK_ITEMS.READ,
    PERMISSIONS.WORK_ITEMS.UPDATE,

    PERMISSIONS.PROFILE.READ,
    PERMISSIONS.PROFILE.UPDATE,

    PERMISSIONS.WORK_ITEMS.CREATE,

     // Settings
    PERMISSIONS.SETTINGS.READ,
    PERMISSIONS.SETTINGS.UPDATE,
  ],
};